---
 S3_BUCKET: "sn-location-tagger-prd"
 locationMasterEndpoint: "http://sn-location-master.smartnews.internal"
 snLocationPlatformEndpoint: "http://sn-location-master.sn-location.dev.smartnews.net"
 locationMasterDB: "sn_location_master"
 locationMasterDBHost: "sn-location-master-ro-presto-prd-1.c6xrdianp1t4.ap-northeast-1.rds.amazonaws.com"
 locationMasterDBUser: "smartnews"
 locationMasterDBPassword: "smartnews"
 use_proxy: "false"
 wikipedia_field: "api/internal/location/v1/wikipedia"
 locationID_field: "api/internal/location/v1/"
 keyword_field: "/api/internal/geocode/v1/keyword"
 keyword_bulk_field: "/api/internal/geocode/v1/bulk/keyword"
 wiki_loc_file: "./src/LT/_DATA/wiki_loc_names_1+2.cleaned-ver1.txt"
 state_code_file: "./src/LT/_DATA/state_code_listing.txt"
 filter_model_path: "./src/LT/_MODEL/NN_model.pkl"
 wiki_entity_file_path: "./src/LT/_DATA/wiki_loc_names_1+2.txt"
 poi_file_path: "./src/LT/_DATA/usa_locations_wiki_entity_info.txt"
 REGION_NAME: "ap-northeast-1"
 KINESIS_STREAM: "us_location_tagger_v2_dev"
