import os

class Meta_config:
    us_states = [
        ["alabama", "al"],
        ["alabama", "ala."],
        ["alaska", "ak"],
        ["arizona", "az"],
        ["arkansas", "ar"],
        ["california", "ca"],
        ["california", "calif."],
        ["colorado", "co"],
        ["connecticut", "ct"],
        ["connecticut", "conn."],
        ["delaware", "de"],
        ["florida", "fl"],
        ["georgia", "ga"],
        ["hawaii", "hi"],
        ["idaho", "id"],
        ["idaho", "ida."],
        ["illinois", "il"],
        ["indiana", "ind."],
        ["iowa", "ia"],
        ["kansas", "ks"],
        ["kansas", "kan."],
        ["kentucky", "ky"],
        ["louisiana", "la"],
        ["maine", "me"],
        ["maryland", "md"],
        ["massachusetts", "ma"],
        ["massachusetts", "mass."],
        ["michigan", "mi"],
        ["minnesota", "mn"],
        ["mississippi", "ms"],
        ["missouri", "mo"],
        ["montana", "mt"],
        ["nebraska", "ne"],
        ["nevada", "nv"],
        ["new hampshire", "nh"],
        ["new jersey", "nj"],
        ["new mexico", "nm"],
        ["new york", "ny"],
        ["north carolina", "nc"],
        ["north dakota", "nd"],
        ["ohio", "oh"],
        ["oklahoma", "ok"],
        ["oregon", "or"],
        ["pennsylvania", "pa"],
        ["rhode island", "ri"],
        ["south carolina", "sc"],
        ["south dakota", "sd"],
        ["tennessee", "tn"],
        ["tennessee", "tenn."],
        ["texas", "tx"],
        ["texas", "tex."],
        ["utah", "ut"],
        ["vermont", "vt"],
        ["virginia", "va"],
        ["washington", "wa"],
        ["washington", "wash."],
        ["west virginia", "wv"],
        ["wisconsin", "wi"],
        ["wisconsin", "wisc."],
        ["wisconsin", "wis."],
        ["wyoming", "wy"],
        ["wyoming", "wyo."],
        ["district of columbia", "dc"],
        ["marshall islands", "mh"]
    ]

    def setup_local_test_env(configs, stage="prd"):
        for k, v in configs.items():
            if k == "S3_BUCKET":
                os.environ[k] = v + f"-{stage}"
                continue
            os.environ[k] = v
